# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-26 22:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='城市名')),
                ('desc', models.CharField(max_length=200, verbose_name='描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
            },
        ),
        migrations.CreateModel(
            name='CourseOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='机构名称')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='机构描述')),
                ('category', models.CharField(choices=[('1', '培训机构'), ('2', '个人'), ('3', '高校')], default='0', max_length=50, verbose_name='机构类别')),
                ('click_nums', models.IntegerField(blank=True, default=0, null=True, verbose_name='点击数')),
                ('fav_nums', models.IntegerField(blank=True, default=0, null=True, verbose_name='收藏数')),
                ('image', models.ImageField(blank=True, null=True, upload_to='org/%Y/%m', verbose_name='logo')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='机构地址')),
                ('students', models.IntegerField(blank=True, default=0, null=True, verbose_name='学习人数')),
                ('course_nums', models.IntegerField(blank=True, default=0, null=True, verbose_name='课程数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='org.CityDict', verbose_name='所在城市')),
            ],
            options={
                'verbose_name': '课程机构',
                'verbose_name_plural': '课程机构',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='教师名称')),
                ('work_years', models.IntegerField(blank=True, default=0, null=True, verbose_name='工作年限')),
                ('work_company', models.CharField(blank=True, max_length=50, null=True, verbose_name='就职公司')),
                ('work_position', models.CharField(blank=True, max_length=50, null=True, verbose_name='公司职位')),
                ('points', models.CharField(blank=True, max_length=50, null=True, verbose_name='教学特点')),
                ('click_nums', models.IntegerField(blank=True, default=0, null=True, verbose_name='点击数')),
                ('fav_nums', models.IntegerField(blank=True, default=0, null=True, verbose_name='收藏数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.CourseOrg', verbose_name='所属机构')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
                'ordering': ('-id',),
            },
        ),
    ]
